# Generated by Django 5.0.4 on 2024-04-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_order_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='orders',
            field=models.ManyToManyField(to='users.order'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='projects',
            field=models.ManyToManyField(to='users.project'),
        ),
    ]
